### ISSUE TITLE
How can I use epubjs-reader?

### ISSUE THREAD

**Issue by mahag** [futurepress/epubjs-angular-reader#30]
What are the steps to go through to be able to use this reader and pass to it my epub files inside my website?Is there any clear documentation availbale?

**Comment by alchzh** [comment]
I know i'm 9 months late but...
First get the repo.
Second open package.json and replace all the "X.X.X-X" and whatnots with "*"
Then run npm install from the root folder
Then unpack your epub file (`unzip your_epub.epub`)
Copy the folder to the src/ folder in epubjs-reader
edit `src/index.html` and change `<epubreader src="/moby-dick/"></epubreader>` to `<epubreader src="/your_epub/"></epubreader>`
Get [epubjs-search](http://github.com/futurepress/epubjs-search)
Follow the instructions there with your_epub
run epubjs-search
edit `src/scripts/directives/epub-reader.js` so that .SEARCH_SERVER is http://localhost:5000 or whatever it is from the previous step
run `node server.js` from root folder of repo
visit localhost:8080
profit
